site_name: CyberTorcs-doc
repo_url: https://github.com/WoodOxen/CyberTorcs-doc
docs_dir: docs
edit_uri: 'blob/master/docs/'
# extra_css: [extra.css]
# extra_javascript: [extra.js]
theme: readthedocs

nav:
- 主页: 'index.md'
- 安装说明: 'installation.md'
- 编程方法介绍:
    - 程序编写接口: 'intro_api.md'
    - 车体控制变量: 'intro_variables.md'
- 常见问题: "faq.md"

markdown_extensions:
  - admonition