# Check https://markdown-docs-zh.readthedocs.io/zh_CN/latest/user-guide/configuration/
# for more MkDocs configuration details

site_name: CyberTorcs-doc
site_url: https://cybertorcs.readthedocs.io/zh_CN/latest/
site_description: CyberTorcs软件的官方网站
site_author: CyberC3 Intelligent Vehicle Labs
repo_url: https://github.com/WoodOxen/CyberTorcs-doc

docs_dir: docs

nav:
  - 主页: "index.md"
  - 简介:
      - 平台结构: "intro_structure.md"
      - 设置菜单介绍: "intro_settings.md"
  - 安装: "install.md"
  - 原理介绍:
      - 车辆动力学模型: "mechanism_car_model.md"
      - PID控制算法: "mechanism_pid.md"
  - 任务介绍:
    - 巡线任务: "task_patrolling.md"
    - 跟车任务: "task_following.md"
    - 泊车任务: "task_parking.md"
  - 样例代码:
      - PID控制: "sample_PID.md"
      - Stanley: "sample_stanley.md"
  - 常见问题: "faq.md"

theme: "readthedocs"

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
